version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    aws-sdk:
      # A pattern can be...
      patterns:
        - "github.com/aws/aws-sdk-go-v2"
        - "github.com/aws/aws-sdk-go-v2/*"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
