name: Build & Pre-Release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'

      - name: Install dependencies
        run: |
          go mod download
          go get github.com/randall77/makefat

      - name: Build
        run: bin/build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          title: "Development release: main branch"
          files: |
            build/*
