name: Build & Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Install dependencies
        run: |
          go mod download
          go install github.com/randall77/makefat@latest

      - name: Build
        run: bin/build

      - uses: actions/upload-artifact@v3
        with:
          name: builds
          path: build/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/*
